staticSites:
  - name: kodipay-web
    buildCommand: echo 'Using pre-built files'
    publishDir: frontend/build/web
    routes:
      - type: rewrite
        source: "/*"
        destination: /index.html
